model:
  class: NODE_CUDA
  latent_size: 29
  num_layers: 7
  layer_hidden_size: 91
  input_size: 3
  output_size: 3
optimizer: !!set
  false: null
data:
  n_samples: 1000
  batch_size: 256
training:
  max_epochs: 1000
  log_every_n_steps: 1
  num_sanity_val_steps: 0
artifacts:
  model_pkl: /home/sofiataveira/Documents/sofia/neuroai/ComputationThruDynamicsBenchmark/models_NODE_9/model.pkl
  datamodule_pkl: /home/sofiataveira/Documents/sofia/neuroai/ComputationThruDynamicsBenchmark/models_NODE_9/datamodule_sim.pkl
  loss_png: /home/sofiataveira/Documents/sofia/neuroai/ComputationThruDynamicsBenchmark/models_NODE_9/loss_curves.png
  loss_csv: /home/sofiataveira/Documents/sofia/neuroai/ComputationThruDynamicsBenchmark/models_NODE_9/loss_curves.csv
